spring:
  application:
    name: "XmlUploader"
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mariadb://localhost:3306/xmluploader
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  port: 9080

management:
  server:
    port: 9081
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    diskSpace:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: "always"

logging:
  level:
    root: INFO
    nl.joost.xmluploader: DEBUG
  file:
    name: "/tmp/logs/xml_uploader.log"


